import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'ar';
export type Direction = 'ltr' | 'rtl';

interface LanguageContextType {
  language: Language;
  direction: Direction;
  isRTL: boolean;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Comprehensive translations object
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'home': 'Home',
    'search': 'Search',
    'packages': 'Packages',
    'flights': 'Flights',
    'transport': 'Transport',
    'hotels': 'Hotels',
    'profile': 'Profile',
    'bookings': 'Bookings',
    'wishlist': 'Wishlist',
    'logout': 'Logout',
    
    // Hero section
    'hero.badge': 'Hajj & Umrah Specialists',
    'hero.title1': 'Your',
    'hero.spiritual': 'spiritual journey',
    'hero.made': 'made',
    'hero.simple': 'simple',
    'hero.description': 'Experience the sacred journey of a lifetime with our expertly curated Hajj and Umrah packages. We handle every detail so you can focus on your spiritual connection.',
    'hero.explorePackages': 'Explore Packages',
    'hero.learnMore': 'Learn More',
    'hero.support247': '24/7 Customer Support',
    'hero.bestPrice': 'Best Price Guarantee',
    'hero.expertGuides': 'Expert Local Guides',
    'hero.securePayments': 'Secure Payments',
    
    // Benefits
    'benefits.whyChoose': 'Why Choose InstaSafar',
    'benefits.makingJourney': 'Making Your Journey',
    'benefits.spiritualComfortable': 'Spiritual & Comfortable',
    'benefits.description': 'We understand the profound significance of Hajj and Umrah in your spiritual life. Every aspect of our service is designed to enhance your sacred journey with comfort, convenience, and deep meaning.',
    'benefits.customizedPackages': 'Customized Packages',
    'benefits.customizedPackagesDesc': 'Tailored spiritual journeys designed specifically for your needs, schedule, and budget preferences',
    'benefits.expertGuidance': 'Expert Spiritual Guidance',
    'benefits.expertGuidanceDesc': 'Knowledgeable guides to help you perform all rituals correctly with deep spiritual meaning',
    'benefits.verifiedTrusted': 'Verified & Trusted',
    'benefits.verifiedTrustedDesc': 'All our service providers are authenticated and verified for your safety and peace of mind',
    'benefits.support24': '24/7 Support',
    'benefits.support24Desc': 'Round-the-clock assistance throughout your sacred journey whenever you need help',
    
    // Stats
    'stats.pilgrimsServed': 'Pilgrims Served',
    'stats.averageRating': 'Average Rating',
    'stats.yearsExperience': 'Years Experience',
    'stats.supportAvailable': 'Support Available',
    'stats.rating': 'Rating',
    'stats.from5000Reviews': 'From 5000+ reviews',
    
    // Search
    'search.title': 'Start Your Sacred Journey',
    'search.subtitle': 'Find the perfect package for your spiritual needs',
    'search.destination': 'Destination',
    'search.selectLocation': 'Select location',
    'search.checkInDate': 'Check-in Date',
    'search.pickDate': 'Pick a date',
    'search.duration': 'Duration',
    'search.selectDuration': 'Select duration',
    'search.duration3': '3 Days',
    'search.duration7': '7 Days',
    'search.duration14': '14 Days',
    'search.duration21': '21 Days',
    'search.duration30': '30 Days',
    'search.searchHotels': 'Search Hotels',
    'search.bothCities': 'Both Cities',
    
    // Cities
    'cities.makkah': 'Makkah',
    'cities.madinah': 'Madinah',
    
    // Testimonials
    'testimonials.location1': 'United Kingdom',
    'testimonials.location2': 'Canada',
    'testimonials.location3': 'United States',
    'testimonials.text1': 'InstaSafar made my Umrah journey absolutely perfect. From the moment I booked until I returned home, every detail was handled with care and professionalism.',
    'testimonials.text2': 'As a first-time visitor to the Holy Cities, I was nervous about the journey. InstaSafar\'s team guided me through everything with patience and expertise.',
    'testimonials.text3': 'The Hajj package was comprehensive and well-organized. The accommodations were excellent and the spiritual guidance made the experience truly meaningful.',
    'testimonials.badge1': 'Verified Pilgrim',
    'testimonials.badge2': 'First-time Pilgrim',
    'testimonials.badge3': 'Hajj Pilgrim',
    
    // Authentication
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.signInTitle': 'Sign in to your account',
    'auth.signUpDescription': 'Sign up to start booking your spiritual journey',
    'auth.signInDescription': 'Enter your email and password below to sign in',
    'auth.createAccount': 'Create an account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.emailPlaceholder': 'your.email@example.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.confirmPasswordPlaceholder': '••••••••',
    'auth.fullNamePlaceholder': 'Your Full Name',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.noAccount': "Don't have an account?",
    'auth.alreadyAccount': 'Already have an account?',
    'auth.areYouProvider': 'Are you a service provider?',
    'auth.registerAsProvider': 'Register here',
    'auth.termsAgreement': 'By registering, you agree to our',
    'auth.termsOfService': 'Terms of Service',
    'auth.and': 'and',
    'auth.privacyPolicy': 'Privacy Policy',
    'auth.registering': 'Creating account...',
    'auth.registerSuccess': 'Registration successful',
    'auth.registerSuccessDescription': 'Your account has been created successfully.',
    'auth.loginSuccess': 'Login Successful',
    'auth.welcomeBack': 'Welcome back to InstaSafar!',
    'auth.authError': 'Authentication Error',
    'auth.authenticating': 'Completing Authentication',
    'auth.pleaseWait': 'Please wait while we authenticate your account...',
    'auth.redirectingToLogin': 'Redirecting to login page...',
    'auth.unexpectedError': 'An unexpected error occurred. Please try again.',
    'auth.quickLogin': 'Quick Login for Demo',
    'auth.loginAsUser': 'Login as User',
    'auth.loginAsProvider': 'Login as Provider',
    'auth.loginAsAdmin': 'Login as Admin',
    'auth.demoNotice': 'Demo accounts are for demonstration purposes only',
    'auth.login.adminTitle': 'Admin Sign In',
    'auth.login.providerTitle': 'Provider Sign In',
    'auth.login.userTab': 'User',
    'auth.login.providerTab': 'Provider',
    'auth.login.adminTab': 'Admin',
    
    // Language switching
    'language.select': 'Select Language',
    'language.changedToEnglish': 'Language changed to English',
    'language.changedToArabic': 'Language changed to Arabic',
    'language.pageWillRefresh': 'The page will refresh to apply changes',
    'language.pageWillRefreshAr': 'The page will refresh to apply changes',
    
    // Common words
    'common.search': 'Search',
    'common.book': 'Book',
    'common.view': 'View',
    'common.details': 'Details',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.update': 'Update',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.clear': 'Clear',
    'common.apply': 'Apply',
    'common.remove': 'Remove',
    'common.select': 'Select',
    'common.choose': 'Choose',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.share': 'Share',
    'common.copy': 'Copy',
    'common.refresh': 'Refresh',
    'common.print': 'Print',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.help': 'Help',
    'common.about': 'About',
    'common.contact': 'Contact',
    'common.support': 'Support',
    'common.settings': 'Settings',
    'common.privacy': 'Privacy',
    'common.terms': 'Terms',
    'common.policy': 'Policy',
    'common.copyright': 'Copyright',
    'common.allRightsReserved': 'All rights reserved',
    'common.currency': 'SAR',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.optional': 'Optional',
    'common.required': 'Required',
    'common.available': 'Available',
    'common.unavailable': 'Unavailable',
    'common.free': 'Free',
    'common.paid': 'Paid',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.tax': 'Tax',
    'common.discount': 'Discount',
    'common.price': 'Price',
    'common.perNight': 'per night',
    'common.perPerson': 'per person',
    'common.adults': 'Adults',
    'common.children': 'Children',
    'common.rooms': 'Rooms',
    'common.nights': 'Nights',
    'common.days': 'Days',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.checkIn': 'Check In',
    'common.checkOut': 'Check Out',
    'common.departure': 'Departure',
    'common.arrival': 'Arrival',
    'common.from': 'From',
    'common.to': 'To',
    'common.rating': 'Rating',
    'common.reviews': 'Reviews',
    'common.review': 'Review',
    'common.location': 'Location',
    'common.address': 'Address',
    'common.phone': 'Phone',
    'common.website': 'Website',
    'common.map': 'Map',
    'common.photos': 'Photos',
    'common.amenities': 'Amenities',
    'common.facilities': 'Facilities',
    'common.services': 'Services',
    'common.features': 'Features',
    'common.description': 'Description',
    'common.overview': 'Overview',
    'common.highlights': 'Highlights',
    'common.included': 'Included',
    'common.excluded': 'Excluded',
    'common.notes': 'Notes',
    'common.policies': 'Policies',
    'common.cancellation': 'Cancellation',
    'common.refund': 'Refund',
    'common.payment': 'Payment',
    'common.checkout': 'Checkout',
    
    // Dashboard
    'dashboard.welcome': 'Welcome',
    'dashboard.overview': 'Dashboard Overview',
    'dashboard.totalBookings': 'Total Bookings',
    'dashboard.totalBookingsDesc': 'Total number of bookings received',
    'dashboard.pendingBookings': 'Pending Bookings',
    'dashboard.pendingBookingsDesc': 'Bookings awaiting confirmation',
    'dashboard.totalRevenue': 'Total Revenue',
    'dashboard.totalRevenueDesc': 'Total revenue from all bookings',
    'dashboard.activeListings': 'Active Listings',
    'dashboard.activeListingsDesc': 'Your active hotel and package listings',
    'dashboard.recentBookings': 'Recent Bookings',
    'dashboard.viewAll': 'View All',
    'dashboard.monthlyBookings': 'Monthly Bookings',
    'dashboard.monthlyBookingsDesc': 'Number of bookings per month',
    'dashboard.revenueTrend': 'Revenue Trend',
    'dashboard.revenueTrendDesc': 'Monthly revenue in SAR',
    'dashboard.bookings': 'Bookings',
    'dashboard.revenue': 'Revenue',
    'dashboard.stats': 'Statistics',
    'dashboard.analytics': 'Analytics',
    'dashboard.reports': 'Reports',
    
    // Admin specific
    'admin.dashboard': 'Admin Dashboard',
    'admin.users': 'Users',
    'admin.providers': 'Providers',
    'admin.systemSettings': 'System Settings',
    'admin.userManagement': 'User Management',
    'admin.providerManagement': 'Provider Management',
    'admin.bookingManagement': 'Booking Management',
    'admin.reviewManagement': 'Review Management',
    'admin.totalUsers': 'Total Users',
    'admin.totalProviders': 'Total Providers',
    'admin.systemHealth': 'System Health',
    'admin.recentActivity': 'Recent Activity',
    
    // Bookings
    'bookings.title': 'My Bookings',
    'bookings.upcoming': 'Upcoming',
    'bookings.past': 'Past',
    'bookings.cancelled': 'Cancelled',
    'bookings.pending': 'Pending',
    'bookings.confirmed': 'Confirmed',
    'bookings.completed': 'Completed',
    'bookings.bookingId': 'Booking ID',
    'bookings.bookingDate': 'Booking Date',
    'bookings.bookingDetails': 'Booking Details',
    'bookings.guestDetails': 'Guest Details',
    'bookings.contactInfo': 'Contact Information',
    'bookings.specialRequests': 'Special Requests',
    'bookings.bookingStatus': 'Booking Status',
    'bookings.paymentStatus': 'Payment Status',
    'bookings.modifyBooking': 'Modify Booking',
    'bookings.cancelBooking': 'Cancel Booking',
    'bookings.downloadVoucher': 'Download Voucher',
    'bookings.noBookings': 'No bookings found',
    'bookings.bookingConfirmed': 'Booking Confirmed',
    'bookings.bookingCancelled': 'Booking Cancelled',
    'bookings.bookingModified': 'Booking Modified',
    
    // Hotels
    'hotels.searchHotels': 'Search Hotels',
    'hotels.featuredHotels': 'Featured Hotels',
    'hotels.hotelDetails': 'Hotel Details',
    'hotels.roomTypes': 'Room Types',
    'hotels.availability': 'Availability',
    'hotels.pricePerNight': 'Price per night',
    'hotels.distanceToHaram': 'Distance to Haram',
    'hotels.starRating': 'Star Rating',
    'hotels.guestRating': 'Guest Rating',
    'hotels.hotelAmenities': 'Hotel Amenities',
    'hotels.roomAmenities': 'Room Amenities',
    'hotels.hotelPolicies': 'Hotel Policies',
    'hotels.cancellationPolicy': 'Cancellation Policy',
    'hotels.checkInTime': 'Check-in Time',
    'hotels.checkOutTime': 'Check-out Time',
    'hotels.selectRoom': 'Select Room',
    'hotels.bookNow': 'Book Now',
    'hotels.viewOnMap': 'View on Map',
    'hotels.hotelPhotos': 'Hotel Photos',
    'hotels.nearbyAttractions': 'Nearby Attractions',
    'hotels.transportOptions': 'Transport Options',
    
    // Packages
    'packages.title': 'Travel Packages',
    'packages.featuredPackages': 'Featured Packages',
    'packages.packageDetails': 'Package Details',
    'packages.packageIncludes': 'Package Includes',
    'packages.itinerary': 'Itinerary',
    'packages.pricePerPerson': 'Price per person',
    'packages.duration': 'Duration',
    'packages.groupSize': 'Group Size',
    'packages.departureDate': 'Departure Date',
    'packages.returnDate': 'Return Date',
    'packages.availableDates': 'Available Dates',
    'packages.packageType': 'Package Type',
    'packages.umrahPackage': 'Umrah Package',
    'packages.hajjPackage': 'Hajj Package',
    'packages.cityTour': 'City Tour',
    'packages.religiousTour': 'Religious Tour',
    'packages.bookPackage': 'Book Package',
    'packages.packageBooking': 'Package Booking',
    'packages.selectDates': 'Select Dates',
    'packages.selectPassengers': 'Select Passengers',
    'packages.packageInformation': 'Package Information',
    
    // Search
    'search.destination': 'Destination',
    'search.checkInDate': 'Check-in Date',
    'search.checkOutDate': 'Check-out Date',
    'search.guests': 'Guests',
    'search.searchHotels': 'Search Hotels',
    'search.searchPackages': 'Search Packages',
    'search.searchFlights': 'Search Flights',
    'search.filters': 'Filters',
    'search.sortBy': 'Sort by',
    'search.priceRange': 'Price Range',
    'search.starRating': 'Star Rating',
    'search.distance': 'Distance',
    'search.amenities': 'Amenities',
    'search.results': 'Results',
    'search.noResults': 'No results found',
    'search.showMore': 'Show More',
    'search.showLess': 'Show Less',
    'search.resultsFound': 'results found',
    'search.clearFilters': 'Clear Filters',
    'search.applyFilters': 'Apply Filters',
    
    // Cities
    'cities.makkah': 'Makkah',
    'cities.madinah': 'Madinah',
    'cities.riyadh': 'Riyadh',
    'cities.jeddah': 'Jeddah',
    'cities.dammam': 'Dammam',
    'cities.taif': 'Taif',
    'cities.abha': 'Abha',
    'cities.tabuk': 'Tabuk',
    'cities.najran': 'Najran',
    'cities.qassim': 'Qassim',
    
    // Months
    'months.jan': 'Jan',
    'months.feb': 'Feb',
    'months.mar': 'Mar',
    'months.apr': 'Apr',
    'months.may': 'May',
    'months.jun': 'Jun',
    'months.jul': 'Jul',
    'months.aug': 'Aug',
    'months.sep': 'Sep',
    'months.oct': 'Oct',
    'months.nov': 'Nov',
    'months.dec': 'Dec',
    
    // Days
    'days.monday': 'Monday',
    'days.tuesday': 'Tuesday',
    'days.wednesday': 'Wednesday',
    'days.thursday': 'Thursday',
    'days.friday': 'Friday',
    'days.saturday': 'Saturday',
    'days.sunday': 'Sunday',
    
    // Errors
    'errors.networkError': 'Network error. Please check your connection.',
    'errors.serverError': 'Server error. Please try again later.',
    'errors.notFound': 'The requested resource was not found.',
    'errors.unauthorized': 'You are not authorized to access this resource.',
    'errors.forbidden': 'Access to this resource is forbidden.',
    'errors.validationError': 'Please check your input and try again.',
    'errors.bookingError': 'There was an error processing your booking.',
    'errors.paymentError': 'Payment failed. Please try again.',
    'errors.fileUploadError': 'File upload failed. Please try again.',
    'errors.sessionExpired': 'Your session has expired. Please log in again.',
    
    // Success messages
    'success.bookingCreated': 'Booking created successfully!',
    'success.paymentCompleted': 'Payment completed successfully!',
    'success.profileUpdated': 'Profile updated successfully!',
    'success.passwordChanged': 'Password changed successfully!',
    'success.emailVerified': 'Email verified successfully!',
    'success.dataExported': 'Data exported successfully!',
    'success.settingsSaved': 'Settings saved successfully!',
  },
  ar: {
    // Navigation
    'home': 'الرئيسية',
    'search': 'البحث',
    'packages': 'الباقات',
    'flights': 'الرحلات',
    'transport': 'النقل',
    'hotels': 'الفنادق',
    'profile': 'الملف الشخصي',
    'bookings': 'الحجوزات',
    'wishlist': 'المفضلة',
    'logout': 'تسجيل الخروج',
    
    // Hero section
    'hero.badge': 'متخصصون في الحج والعمرة',
    'hero.title1': 'رحلتك',
    'hero.spiritual': 'الروحانية',
    'hero.made': 'أصبحت',
    'hero.simple': 'بسيطة',
    'hero.description': 'اختبر الرحلة المقدسة التي تدوم مدى الحياة مع باقات الحج والعمرة المنسقة بخبرة. نحن نتولى كل التفاصيل حتى تركز على ارتباطك الروحاني.',
    'hero.explorePackages': 'استكشف الباقات',
    'hero.learnMore': 'تعرف أكثر',
    'hero.support247': 'دعم العملاء على مدار الساعة',
    'hero.bestPrice': 'ضمان أفضل سعر',
    'hero.expertGuides': 'أدلاء محليون خبراء',
    'hero.securePayments': 'مدفوعات آمنة',
    
    // Benefits
    'benefits.whyChoose': 'لماذا تختار إنستا سفر',
    'benefits.makingJourney': 'نجعل رحلتك',
    'benefits.spiritualComfortable': 'روحانية ومريحة',
    'benefits.description': 'نحن ندرك الأهمية العميقة للحج والعمرة في حياتك الروحية. كل جانب من خدمتنا مصمم لتعزيز رحلتك المقدسة بالراحة والسهولة والمعنى العميق.',
    'benefits.customizedPackages': 'باقات مخصصة',
    'benefits.customizedPackagesDesc': 'رحلات روحانية مخصصة مصممة خصيصاً لاحتياجاتك وجدولك الزمني وتفضيلات ميزانيتك',
    'benefits.expertGuidance': 'إرشاد روحاني خبير',
    'benefits.expertGuidanceDesc': 'أدلاء ذوو خبرة لمساعدتك في أداء جميع الطقوس بشكل صحيح مع معنى روحاني عميق',
    'benefits.verifiedTrusted': 'موثق وموثوق',
    'benefits.verifiedTrustedDesc': 'جميع مقدمي الخدمات لدينا موثقون ومعتمدون من أجل سلامتك وراحة بالك',
    'benefits.support24': 'دعم على مدار الساعة',
    'benefits.support24Desc': 'مساعدة على مدار الساعة طوال رحلتك المقدسة متى احتجت للمساعدة',
    
    // Stats
    'stats.pilgrimsServed': 'حاج ومعتمر تم خدمتهم',
    'stats.averageRating': 'متوسط التقييم',
    'stats.yearsExperience': 'سنوات الخبرة',
    'stats.supportAvailable': 'الدعم متاح',
    'stats.rating': 'التقييم',
    'stats.from5000Reviews': 'من أكثر من 5000 مراجعة',
    
    // Search
    'search.title': 'ابدأ رحلتك المقدسة',
    'search.subtitle': 'اعثر على الباقة المثالية لاحتياجاتك الروحانية',
    'search.destination': 'الوجهة',
    'search.selectLocation': 'اختر الموقع',
    'search.checkInDate': 'تاريخ الوصول',
    'search.pickDate': 'اختر تاريخاً',
    'search.duration': 'المدة',
    'search.selectDuration': 'اختر المدة',
    'search.duration3': '3 أيام',
    'search.duration7': '7 أيام',
    'search.duration14': '14 يوماً',
    'search.duration21': '21 يوماً',
    'search.duration30': '30 يوماً',
    'search.searchHotels': 'البحث عن فنادق',
    'search.bothCities': 'كلا المدينتين',
    
    // Cities
    'cities.makkah': 'مكة المكرمة',
    'cities.madinah': 'المدينة المنورة',
    
    // Testimonials
    'testimonials.location1': 'المملكة المتحدة',
    'testimonials.location2': 'كندا',
    'testimonials.location3': 'الولايات المتحدة',
    'testimonials.text1': 'جعل إنستا سفر رحلة العمرة الخاصة بي مثالية تماماً. من لحظة الحجز حتى عودتي للوطن، تم التعامل مع كل التفاصيل بعناية ومهنية.',
    'testimonials.text2': 'كوني زائرة لأول مرة للمدن المقدسة، كنت متوترة بشأن الرحلة. فريق إنستا سفر أرشدني عبر كل شيء بصبر وخبرة.',
    'testimonials.text3': 'كانت باقة الحج شاملة ومنظمة بشكل جيد. كانت أماكن الإقامة ممتازة والإرشاد الروحاني جعل التجربة ذات معنى حقيقي.',
    'testimonials.badge1': 'حاج معتمد',
    'testimonials.badge2': 'حاج لأول مرة',
    'testimonials.badge3': 'حاج',
    
    // Authentication
    'auth.signIn': 'تسجيل الدخول',
    'auth.signUp': 'التسجيل',
    'auth.login': 'دخول',
    'auth.register': 'تسجيل',
    'auth.signInTitle': 'تسجيل الدخول إلى حسابك',
    'auth.signUpDescription': 'سجل للبدء في حجز رحلتك الروحانية',
    'auth.signInDescription': 'أدخل بريدك الإلكتروني وكلمة المرور أدناه لتسجيل الدخول',
    'auth.createAccount': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.fullName': 'الاسم الكامل',
    'auth.emailPlaceholder': 'your.email@example.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.confirmPasswordPlaceholder': '••••••••',
    'auth.fullNamePlaceholder': 'اسمك الكامل',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.alreadyAccount': 'لديك حساب بالفعل؟',
    'auth.areYouProvider': 'هل أنت مقدم خدمة؟',
    'auth.registerAsProvider': 'سجل هنا',
    'auth.termsAgreement': 'بالتسجيل، أنت توافق على',
    'auth.termsOfService': 'شروط الخدمة',
    'auth.and': 'و',
    'auth.privacyPolicy': 'سياسة الخصوصية',
    'auth.registering': 'جاري إنشاء الحساب...',
    'auth.registerSuccess': 'تم التسجيل بنجاح',
    'auth.registerSuccessDescription': 'تم إنشاء حسابك بنجاح.',
    'auth.loginSuccess': 'تم تسجيل الدخول بنجاح',
    'auth.welcomeBack': 'مرحباً بعودتك إلى إنستا سفر!',
    'auth.authError': 'خطأ في المصادقة',
    'auth.authenticating': 'جاري إكمال المصادقة',
    'auth.pleaseWait': 'يرجى الانتظار بينما نتحقق من حسابك...',
    'auth.redirectingToLogin': 'جاري التوجيه إلى صفحة تسجيل الدخول...',
    'auth.unexpectedError': 'حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.',
    'auth.quickLogin': 'تسجيل دخول سريع للعرض التوضيحي',
    'auth.loginAsUser': 'تسجيل الدخول كمستخدم',
    'auth.loginAsProvider': 'تسجيل الدخول كمقدم خدمة',
    'auth.loginAsAdmin': 'تسجيل الدخول كمدير',
    'auth.demoNotice': 'حسابات العرض التوضيحي لأغراض التوضيح فقط',
    'auth.login.adminTitle': 'تسجيل دخول المدير',
    'auth.login.providerTitle': 'تسجيل دخول مقدم الخدمة',
    'auth.login.userTab': 'مستخدم',
    'auth.login.providerTab': 'مقدم خدمة',
    'auth.login.adminTab': 'مدير',
    
    // Language switching
    'language.select': 'اختر اللغة',
    'language.changedToEnglish': 'تم تغيير اللغة إلى الإنجليزية',
    'language.changedToArabic': 'تم تغيير اللغة إلى العربية',
    'language.pageWillRefresh': 'ستتم إعادة تحميل الصفحة لتطبيق التغييرات',
    'language.pageWillRefreshAr': 'ستتم إعادة تحميل الصفحة لتطبيق التغييرات',
    
    // Common words
    'common.search': 'البحث',
    'common.book': 'حجز',
    'common.view': 'عرض',
    'common.details': 'التفاصيل',
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.cancel': 'إلغاء',
    'common.confirm': 'تأكيد',
    'common.save': 'حفظ',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.add': 'إضافة',
    'common.update': 'تحديث',
    'common.close': 'إغلاق',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.submit': 'إرسال',
    'common.reset': 'إعادة تعيين',
    'common.filter': 'تصفية',
    'common.sort': 'ترتيب',
    'common.clear': 'مسح',
    'common.apply': 'تطبيق',
    'common.remove': 'إزالة',
    'common.select': 'اختيار',
    'common.choose': 'اختر',
    'common.upload': 'رفع',
    'common.download': 'تحميل',
    'common.share': 'مشاركة',
    'common.copy': 'نسخ',
    'common.refresh': 'تحديث',
    'common.print': 'طباعة',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
    'common.help': 'مساعدة',
    'common.about': 'حول',
    'common.contact': 'اتصال',
    'common.support': 'دعم',
    'common.settings': 'إعدادات',
    'common.privacy': 'خصوصية',
    'common.terms': 'شروط',
    'common.policy': 'سياسة',
    'common.copyright': 'حقوق الطبع والنشر',
    'common.allRightsReserved': 'جميع الحقوق محفوظة',
    'common.currency': 'ر.س',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.optional': 'اختياري',
    'common.required': 'مطلوب',
    'common.available': 'متاح',
    'common.unavailable': 'غير متاح',
    'common.free': 'مجاني',
    'common.paid': 'مدفوع',
    'common.total': 'المجموع',
    'common.subtotal': 'المجموع الجزئي',
    'common.tax': 'الضريبة',
    'common.discount': 'خصم',
    'common.price': 'السعر',
    'common.perNight': 'لكل ليلة',
    'common.perPerson': 'لكل شخص',
    'common.adults': 'البالغون',
    'common.children': 'الأطفال',
    'common.rooms': 'الغرف',
    'common.nights': 'الليالي',
    'common.days': 'الأيام',
    'common.date': 'التاريخ',
    'common.time': 'الوقت',
    'common.checkIn': 'تسجيل الوصول',
    'common.checkOut': 'تسجيل المغادرة',
    'common.departure': 'المغادرة',
    'common.arrival': 'الوصول',
    'common.from': 'من',
    'common.to': 'إلى',
    'common.rating': 'التقييم',
    'common.reviews': 'المراجعات',
    'common.review': 'مراجعة',
    'common.location': 'الموقع',
    'common.address': 'العنوان',
    'common.phone': 'الهاتف',
    'common.website': 'الموقع الإلكتروني',
    'common.map': 'الخريطة',
    'common.photos': 'الصور',
    'common.amenities': 'المرافق',
    'common.facilities': 'التسهيلات',
    'common.services': 'الخدمات',
    'common.features': 'المميزات',
    'common.description': 'الوصف',
    'common.overview': 'نظرة عامة',
    'common.highlights': 'النقاط المميزة',
    'common.included': 'مشمول',
    'common.excluded': 'غير مشمول',
    'common.notes': 'ملاحظات',
    'common.policies': 'السياسات',
    'common.cancellation': 'الإلغاء',
    'common.refund': 'الاسترداد',
    'common.payment': 'الدفع',
    'common.checkout': 'الدفع',
    
    // Dashboard
    'dashboard.welcome': 'أهلاً وسهلاً',
    'dashboard.overview': 'نظرة عامة على لوحة التحكم',
    'dashboard.totalBookings': 'إجمالي الحجوزات',
    'dashboard.totalBookingsDesc': 'العدد الإجمالي للحجوزات المستلمة',
    'dashboard.pendingBookings': 'الحجوزات المعلقة',
    'dashboard.pendingBookingsDesc': 'الحجوزات في انتظار التأكيد',
    'dashboard.totalRevenue': 'إجمالي الإيرادات',
    'dashboard.totalRevenueDesc': 'إجمالي الإيرادات من جميع الحجوزات',
    'dashboard.activeListings': 'القوائم النشطة',
    'dashboard.activeListingsDesc': 'قوائم الفنادق والباقات النشطة الخاصة بك',
    'dashboard.recentBookings': 'الحجوزات الأخيرة',
    'dashboard.viewAll': 'عرض الكل',
    'dashboard.monthlyBookings': 'الحجوزات الشهرية',
    'dashboard.monthlyBookingsDesc': 'عدد الحجوزات شهرياً',
    'dashboard.revenueTrend': 'اتجاه الإيرادات',
    'dashboard.revenueTrendDesc': 'الإيرادات الشهرية بالريال السعودي',
    'dashboard.bookings': 'الحجوزات',
    'dashboard.revenue': 'الإيرادات',
    'dashboard.stats': 'الإحصائيات',
    'dashboard.analytics': 'التحليلات',
    'dashboard.reports': 'التقارير',
    
    // Admin specific
    'admin.dashboard': 'لوحة تحكم المدير',
    'admin.users': 'المستخدمون',
    'admin.providers': 'مقدمو الخدمات',
    'admin.systemSettings': 'إعدادات النظام',
    'admin.userManagement': 'إدارة المستخدمين',
    'admin.providerManagement': 'إدارة مقدمي الخدمات',
    'admin.bookingManagement': 'إدارة الحجوزات',
    'admin.reviewManagement': 'إدارة المراجعات',
    'admin.totalUsers': 'إجمالي المستخدمين',
    'admin.totalProviders': 'إجمالي مقدمي الخدمات',
    'admin.systemHealth': 'صحة النظام',
    'admin.recentActivity': 'النشاط الأخير',
    
    // Bookings
    'bookings.title': 'حجوزاتي',
    'bookings.upcoming': 'القادمة',
    'bookings.past': 'السابقة',
    'bookings.cancelled': 'الملغاة',
    'bookings.pending': 'معلقة',
    'bookings.confirmed': 'مؤكدة',
    'bookings.completed': 'مكتملة',
    'bookings.bookingId': 'رقم الحجز',
    'bookings.bookingDate': 'تاريخ الحجز',
    'bookings.bookingDetails': 'تفاصيل الحجز',
    'bookings.guestDetails': 'تفاصيل الضيف',
    'bookings.contactInfo': 'معلومات الاتصال',
    'bookings.specialRequests': 'الطلبات الخاصة',
    'bookings.bookingStatus': 'حالة الحجز',
    'bookings.paymentStatus': 'حالة الدفع',
    'bookings.modifyBooking': 'تعديل الحجز',
    'bookings.cancelBooking': 'إلغاء الحجز',
    'bookings.downloadVoucher': 'تحميل القسيمة',
    'bookings.noBookings': 'لا توجد حجوزات',
    'bookings.bookingConfirmed': 'تم تأكيد الحجز',
    'bookings.bookingCancelled': 'تم إلغاء الحجز',
    'bookings.bookingModified': 'تم تعديل الحجز',
    
    // Hotels
    'hotels.searchHotels': 'البحث عن فنادق',
    'hotels.featuredHotels': 'الفنادق المميزة',
    'hotels.hotelDetails': 'تفاصيل الفندق',
    'hotels.roomTypes': 'أنواع الغرف',
    'hotels.availability': 'التوفر',
    'hotels.pricePerNight': 'السعر لكل ليلة',
    'hotels.distanceToHaram': 'المسافة إلى الحرم',
    'hotels.starRating': 'تصنيف النجوم',
    'hotels.guestRating': 'تقييم الضيوف',
    'hotels.hotelAmenities': 'مرافق الفندق',
    'hotels.roomAmenities': 'مرافق الغرفة',
    'hotels.hotelPolicies': 'سياسات الفندق',
    'hotels.cancellationPolicy': 'سياسة الإلغاء',
    'hotels.checkInTime': 'وقت تسجيل الوصول',
    'hotels.checkOutTime': 'وقت تسجيل المغادرة',
    'hotels.selectRoom': 'اختر الغرفة',
    'hotels.bookNow': 'احجز الآن',
    'hotels.viewOnMap': 'عرض على الخريطة',
    'hotels.hotelPhotos': 'صور الفندق',
    'hotels.nearbyAttractions': 'المعالم القريبة',
    'hotels.transportOptions': 'خيارات النقل',
    
    // Packages
    'packages.title': 'باقات السفر',
    'packages.featuredPackages': 'الباقات المميزة',
    'packages.packageDetails': 'تفاصيل الباقة',
    'packages.packageIncludes': 'تشمل الباقة',
    'packages.itinerary': 'خط الرحلة',
    'packages.pricePerPerson': 'السعر لكل شخص',
    'packages.duration': 'المدة',
    'packages.groupSize': 'حجم المجموعة',
    'packages.departureDate': 'تاريخ المغادرة',
    'packages.returnDate': 'تاريخ العودة',
    'packages.availableDates': 'التواريخ المتاحة',
    'packages.packageType': 'نوع الباقة',
    'packages.umrahPackage': 'باقة عمرة',
    'packages.hajjPackage': 'باقة حج',
    'packages.cityTour': 'جولة في المدينة',
    'packages.religiousTour': 'جولة دينية',
    'packages.bookPackage': 'احجز الباقة',
    'packages.packageBooking': 'حجز الباقة',
    'packages.selectDates': 'اختر التواريخ',
    'packages.selectPassengers': 'اختر المسافرين',
    'packages.packageInformation': 'معلومات الباقة',
    
    // Search
    'search.title': 'ابدأ رحلتك المقدسة',
    'search.subtitle': 'اعثر على الباقة المثالية لاحتياجاتك الروحانية',
    'search.destination': 'الوجهة',
    'search.selectLocation': 'اختر الموقع',
    'search.checkInDate': 'تاريخ الوصول',
    'search.pickDate': 'اختر تاريخاً',
    'search.duration': 'المدة',
    'search.selectDuration': 'اختر المدة',
    'search.duration3': '3 أيام',
    'search.duration7': '7 أيام',
    'search.duration14': '14 يوماً',
    'search.duration21': '21 يوماً',
    'search.duration30': '30 يوماً',
    'search.searchHotels': 'البحث عن فنادق',
    'search.bothCities': 'كلا المدينتين',
    
    // Cities
    'cities.makkah': 'مكة المكرمة',
    'cities.madinah': 'المدينة المنورة',
    
    // Testimonials
    'testimonials.location1': 'المملكة المتحدة',
    'testimonials.location2': 'كندا',
    'testimonials.location3': 'الولايات المتحدة',
    'testimonials.text1': 'جعل إنستا سفر رحلة العمرة الخاصة بي مثالية تماماً. من لحظة الحجز حتى عودتي للوطن، تم التعامل مع كل التفاصيل بعناية ومهنية.',
    'testimonials.text2': 'كوني زائرة لأول مرة للمدن المقدسة، كنت متوترة بشأن الرحلة. فريق إنستا سفر أرشدني عبر كل شيء بصبر وخبرة.',
    'testimonials.text3': 'كانت باقة الحج شاملة ومنظمة بشكل جيد. كانت أماكن الإقامة ممتازة والإرشاد الروحاني جعل التجربة ذات معنى حقيقي.',
    'testimonials.badge1': 'حاج معتمد',
    'testimonials.badge2': 'حاج لأول مرة',
    'testimonials.badge3': 'حاج',
    
    // Authentication
    'auth.signIn': 'تسجيل الدخول',
    'auth.signUp': 'التسجيل',
    'auth.login': 'دخول',
    'auth.register': 'تسجيل',
    'auth.signInTitle': 'تسجيل الدخول إلى حسابك',
    'auth.signUpDescription': 'سجل للبدء في حجز رحلتك الروحانية',
    'auth.signInDescription': 'أدخل بريدك الإلكتروني وكلمة المرور أدناه لتسجيل الدخول',
    'auth.createAccount': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.fullName': 'الاسم الكامل',
    'auth.emailPlaceholder': 'your.email@example.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.confirmPasswordPlaceholder': '••••••••',
    'auth.fullNamePlaceholder': 'اسمك الكامل',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.alreadyAccount': 'لديك حساب بالفعل؟',
    'auth.areYouProvider': 'هل أنت مقدم خدمة؟',
    'auth.registerAsProvider': 'سجل هنا',
    'auth.termsAgreement': 'بالتسجيل، أنت توافق على',
    'auth.termsOfService': 'شروط الخدمة',
    'auth.and': 'و',
    'auth.privacyPolicy': 'سياسة الخصوصية',
    'auth.registering': 'جاري إنشاء الحساب...',
    'auth.registerSuccess': 'تم التسجيل بنجاح',
    'auth.registerSuccessDescription': 'تم إنشاء حسابك بنجاح.',
    'auth.loginSuccess': 'تم تسجيل الدخول بنجاح',
    'auth.welcomeBack': 'مرحباً بعودتك إلى إنستا سفر!',
    'auth.authError': 'خطأ في المصادقة',
    'auth.authenticating': 'جاري إكمال المصادقة',
    'auth.pleaseWait': 'يرجى الانتظار بينما نتحقق من حسابك...',
    'auth.redirectingToLogin': 'جاري التوجيه إلى صفحة تسجيل الدخول...',
    'auth.unexpectedError': 'حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.',
    'auth.quickLogin': 'تسجيل دخول سريع للعرض التوضيحي',
    'auth.loginAsUser': 'تسجيل الدخول كمستخدم',
    'auth.loginAsProvider': 'تسجيل الدخول كمقدم خدمة',
    'auth.loginAsAdmin': 'تسجيل الدخول كمدير',
    'auth.demoNotice': 'حسابات العرض التوضيحي لأغراض التوضيح فقط',
    'auth.login.adminTitle': 'تسجيل دخول المدير',
    'auth.login.providerTitle': 'تسجيل دخول مقدم الخدمة',
    'auth.login.userTab': 'مستخدم',
    'auth.login.providerTab': 'مقدم خدمة',
    'auth.login.adminTab': 'مدير',
    
    // Language switching
    'language.select': 'اختر اللغة',
    'language.changedToEnglish': 'تم تغيير اللغة إلى الإنجليزية',
    'language.changedToArabic': 'تم تغيير اللغة إلى العربية',
    'language.pageWillRefresh': 'ستتم إعادة تحميل الصفحة لتطبيق التغييرات',
    'language.pageWillRefreshAr': 'ستتم إعادة تحميل الصفحة لتطبيق التغييرات',
    
    // Common words
    'common.search': 'البحث',
    'common.book': 'حجز',
    'common.view': 'عرض',
    'common.details': 'التفاصيل',
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.cancel': 'إلغاء',
    'common.confirm': 'تأكيد',
    'common.save': 'حفظ',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.add': 'إضافة',
    'common.update': 'تحديث',
    'common.close': 'إغلاق',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.submit': 'إرسال',
    'common.reset': 'إعادة تعيين',
    'common.filter': 'تصفية',
    'common.sort': 'ترتيب',
    'common.clear': 'مسح',
    'common.apply': 'تطبيق',
    'common.remove': 'إزالة',
    'common.select': 'اختيار',
    'common.choose': 'اختر',
    'common.upload': 'رفع',
    'common.download': 'تحميل',
    'common.share': 'مشاركة',
    'common.copy': 'نسخ',
    'common.refresh': 'تحديث',
    'common.print': 'طباعة',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
    'common.help': 'مساعدة',
    'common.about': 'حول',
    'common.contact': 'اتصال',
    'common.support': 'دعم',
    'common.settings': 'إعدادات',
    'common.privacy': 'خصوصية',
    'common.terms': 'شروط',
    'common.policy': 'سياسة',
    'common.copyright': 'حقوق الطبع والنشر',
    'common.allRightsReserved': 'جميع الحقوق محفوظة',
    'common.currency': 'ر.س',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.optional': 'اختياري',
    'common.required': 'مطلوب',
    'common.available': 'متاح',
    'common.unavailable': 'غير متاح',
    'common.free': 'مجاني',
    'common.paid': 'مدفوع',
    'common.total': 'المجموع',
    'common.subtotal': 'المجموع الجزئي',
    'common.tax': 'الضريبة',
    'common.discount': 'خصم',
    'common.price': 'السعر',
    'common.perNight': 'لكل ليلة',
    'common.perPerson': 'لكل شخص',
    'common.adults': 'البالغون',
    'common.children': 'الأطفال',
    'common.rooms': 'الغرف',
    'common.nights': 'الليالي',
    'common.days': 'الأيام',
    'common.date': 'التاريخ',
    'common.time': 'الوقت',
    'common.checkIn': 'تسجيل الوصول',
    'common.checkOut': 'تسجيل المغادرة',
    'common.departure': 'المغادرة',
    'common.arrival': 'الوصول',
    'common.from': 'من',
    'common.to': 'إلى',
    'common.rating': 'التقييم',
    'common.reviews': 'المراجعات',
    'common.review': 'مراجعة',
    'common.location': 'الموقع',
    'common.address': 'العنوان',
    'common.phone': 'الهاتف',
    'common.website': 'الموقع الإلكتروني',
    'common.map': 'الخريطة',
    'common.photos': 'الصور',
    'common.amenities': 'المرافق',
    'common.facilities': 'التسهيلات',
    'common.services': 'الخدمات',
    'common.features': 'المميزات',
    'common.description': 'الوصف',
    'common.overview': 'نظرة عامة',
    'common.highlights': 'النقاط المميزة',
    'common.included': 'مشمول',
    'common.excluded': 'غير مشمول',
    'common.notes': 'ملاحظات',
    'common.policies': 'السياسات',
    'common.cancellation': 'الإلغاء',
    'common.refund': 'الاسترداد',
    'common.payment': 'الدفع',
    'common.checkout': 'الدفع',
    
    // Dashboard
    'dashboard.welcome': 'أهلاً وسهلاً',
    'dashboard.overview': 'نظرة عامة على لوحة التحكم',
    'dashboard.totalBookings': 'إجمالي الحجوزات',
    'dashboard.totalBookingsDesc': 'العدد الإجمالي للحجوزات المستلمة',
    'dashboard.pendingBookings': 'الحجوزات المعلقة',
    'dashboard.pendingBookingsDesc': 'الحجوزات في انتظار التأكيد',
    'dashboard.totalRevenue': 'إجمالي الإيرادات',
    'dashboard.totalRevenueDesc': 'إجمالي الإيرادات من جميع الحجوزات',
    'dashboard.activeListings': 'القوائم النشطة',
    'dashboard.activeListingsDesc': 'قوائم الفنادق والباقات النشطة الخاصة بك',
    'dashboard.recentBookings': 'الحجوزات الأخيرة',
    'dashboard.viewAll': 'عرض الكل',
    'dashboard.monthlyBookings': 'الحجوزات الشهرية',
    'dashboard.monthlyBookingsDesc': 'عدد الحجوزات شهرياً',
    'dashboard.revenueTrend': 'اتجاه الإيرادات',
    'dashboard.revenueTrendDesc': 'الإيرادات الشهرية بالريال السعودي',
    'dashboard.bookings': 'الحجوزات',
    'dashboard.revenue': 'الإيرادات',
    'dashboard.stats': 'الإحصائيات',
    'dashboard.analytics': 'التحليلات',
    'dashboard.reports': 'التقارير',
    
    // Admin specific
    'admin.dashboard': 'لوحة تحكم المدير',
    'admin.users': 'المستخدمون',
    'admin.providers': 'مقدمو الخدمات',
    'admin.systemSettings': 'إعدادات النظام',
    'admin.userManagement': 'إدارة المستخدمين',
    'admin.providerManagement': 'إدارة مقدمي الخدمات',
    'admin.bookingManagement': 'إدارة الحجوزات',
    'admin.reviewManagement': 'إدارة المراجعات',
    'admin.totalUsers': 'إجمالي المستخدمين',
    'admin.totalProviders': 'إجمالي مقدمي الخدمات',
    'admin.systemHealth': 'صحة النظام',
    'admin.recentActivity': 'النشاط الأخير',
    
    // Bookings
    'bookings.title': 'حجوزاتي',
    'bookings.upcoming': 'القادمة',
    'bookings.past': 'السابقة',
    'bookings.cancelled': 'الملغاة',
    'bookings.pending': 'معلقة',
    'bookings.confirmed': 'مؤكدة',
    'bookings.completed': 'مكتملة',
    'bookings.bookingId': 'رقم الحجز',
    'bookings.bookingDate': 'تاريخ الحجز',
    'bookings.bookingDetails': 'تفاصيل الحجز',
    'bookings.guestDetails': 'تفاصيل الضيف',
    'bookings.contactInfo': 'معلومات الاتصال',
    'bookings.specialRequests': 'الطلبات الخاصة',
    'bookings.bookingStatus': 'حالة الحجز',
    'bookings.paymentStatus': 'حالة الدفع',
    'bookings.modifyBooking': 'تعديل الحجز',
    'bookings.cancelBooking': 'إلغاء الحجز',
    'bookings.downloadVoucher': 'تحميل القسيمة',
    'bookings.noBookings': 'لا توجد حجوزات',
    'bookings.bookingConfirmed': 'تم تأكيد الحجز',
    'bookings.bookingCancelled': 'تم إلغاء الحجز',
    'bookings.bookingModified': 'تم تعديل الحجز',
    
    // Hotels
    'hotels.searchHotels': 'البحث عن فنادق',
    'hotels.featuredHotels': 'الفنادق المميزة',
    'hotels.hotelDetails': 'تفاصيل الفندق',
    'hotels.roomTypes': 'أنواع الغرف',
    'hotels.availability': 'التوفر',
    'hotels.pricePerNight': 'السعر لكل ليلة',
    'hotels.distanceToHaram': 'المسافة إلى الحرم',
    'hotels.starRating': 'تصنيف النجوم',
    'hotels.guestRating': 'تقييم الضيوف',
    'hotels.hotelAmenities': 'مرافق الفندق',
    'hotels.roomAmenities': 'مرافق الغرفة',
    'hotels.hotelPolicies': 'سياسات الفندق',
    'hotels.cancellationPolicy': 'سياسة الإلغاء',
    'hotels.checkInTime': 'وقت تسجيل الوصول',
    'hotels.checkOutTime': 'وقت تسجيل المغادرة',
    'hotels.selectRoom': 'اختر الغرفة',
    'hotels.bookNow': 'احجز الآن',
    'hotels.viewOnMap': 'عرض على الخريطة',
    'hotels.hotelPhotos': 'صور الفندق',
    'hotels.nearbyAttractions': 'المعالم القريبة',
    'hotels.transportOptions': 'خيارات النقل',
    
    // Packages
    'packages.title': 'باقات السفر',
    'packages.featuredPackages': 'الباقات المميزة',
    'packages.packageDetails': 'تفاصيل الباقة',
    'packages.packageIncludes': 'تشمل الباقة',
    'packages.itinerary': 'خط الرحلة',
    'packages.pricePerPerson': 'السعر لكل شخص',
    'packages.duration': 'المدة',
    'packages.groupSize': 'حجم المجموعة',
    'packages.departureDate': 'تاريخ المغادرة',
    'packages.returnDate': 'تاريخ العودة',
    'packages.availableDates': 'التواريخ المتاحة',
    'packages.packageType': 'نوع الباقة',
    'packages.umrahPackage': 'باقة عمرة',
    'packages.hajjPackage': 'باقة حج',
    'packages.cityTour': 'جولة في المدينة',
    'packages.religiousTour': 'جولة دينية',
    'packages.bookPackage': 'احجز الباقة',
    'packages.packageBooking': 'حجز الباقة',
    'packages.selectDates': 'اختر التواريخ',
    'packages.selectPassengers': 'اختر المسافرين',
    'packages.packageInformation': 'معلومات الباقة',
    
    // Search
    'search.title': 'ابدأ رحلتك المقدسة',
    'search.subtitle': 'اعثر على الباقة المثالية لاحتياجاتك الروحانية',
    'search.destination': 'الوجهة',
    'search.selectLocation': 'اختر الموقع',
    'search.checkInDate': 'تاريخ الوصول',
    'search.pickDate': 'اختر تاريخاً',
    'search.duration': 'المدة',
    'search.selectDuration': 'اختر المدة',
    'search.duration3': '3 أيام',
    'search.duration7': '7 أيام',
    'search.duration14': '14 يوماً',
    'search.duration21': '21 يوماً',
    'search.duration30': '30 يوماً',
    'search.searchHotels': 'البحث عن فنادق',
    'search.bothCities': 'كلا المدينتين',
    
    // Cities
    'cities.makkah': 'مكة المكرمة',
    'cities.madinah': 'المدينة المنورة',
    
    // Testimonials
    'testimonials.location1': 'المملكة المتحدة',
    'testimonials.location2': 'كندا',
    'testimonials.location3': 'الولايات المتحدة',
    'testimonials.text1': 'جعل إنستا سفر رحلة العمرة الخاصة بي مثالية تماماً. من لحظة الحجز حتى عودتي للوطن، تم التعامل مع كل التفاصيل بعناية ومهنية.',
    'testimonials.text2': 'كوني زائرة لأول مرة للمدن المقدسة، كنت متوترة بشأن الرحلة. فريق إنستا سفر أرشدني عبر كل شيء بصبر وخبرة.',
    'testimonials.text3': 'كانت باقة الحج شاملة ومنظمة بشكل جيد. كانت أماكن الإقامة ممتازة والإرشاد الروحاني جعل التجربة ذات معنى حقيقي.',
    'testimonials.badge1': 'حاج معتمد',
    'testimonials.badge2': 'حاج لأول مرة',
    'testimonials.badge3': 'حاج',
    
    // Authentication
    'auth.signIn': 'تسجيل الدخول',
    'auth.signUp': 'التسجيل',
    'auth.login': 'دخول',
    'auth.register': 'تسجيل',
    'auth.signInTitle': 'تسجيل الدخول إلى حسابك',
    'auth.signUpDescription': 'سجل للبدء في حجز رحلتك الروحانية',
    'auth.signInDescription': 'أدخل بريدك الإلكتروني وكلمة المرور أدناه لتسجيل الدخول',
    'auth.createAccount': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.fullName': 'الاسم الكامل',
    'auth.emailPlaceholder': 'your.email@example.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.confirmPasswordPlaceholder': '••••••••',
    'auth.fullNamePlaceholder': 'اسمك الكامل',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.alreadyAccount': 'لديك حساب بالفعل؟',
    'auth.areYouProvider': 'هل أنت مقدم خدمة؟',
    'auth.registerAsProvider': 'سجل هنا',
    'auth.termsAgreement': 'بالتسجيل، أنت توافق على',
    'auth.termsOfService': 'شروط الخدمة',
    'auth.and': 'و',
    'auth.privacyPolicy': 'سياسة الخصوصية',
    'auth.registering': 'جاري إنشاء الحساب...',
    'auth.registerSuccess': 'تم التسجيل بنجاح',
    'auth.registerSuccessDescription': 'تم إنشاء حسابك بنجاح.',
    'auth.loginSuccess': 'تم تسجيل الدخول بنجاح',
    'auth.welcomeBack': 'مرحباً بعودتك إلى إنستا سفر!',
    'auth.authError': 'خطأ في المصادقة',
    'auth.authenticating': 'جاري إكمال المصادقة',
    'auth.pleaseWait': 'يرجى الانتظار بينما نتحقق من حسابك...',
    'auth.redirectingToLogin': 'جاري التوجيه إلى صفحة تسجيل الدخول...',
    'auth.unexpectedError': 'حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.',
    'auth.quickLogin': 'تسجيل دخول سريع للعرض التوضيحي',
    'auth.loginAsUser': 'تسجيل الدخول كمستخدم',
    'auth.loginAsProvider': 'تسجيل الدخول كمقدم خدمة',
    'auth.loginAsAdmin': 'تسجيل الدخول كمدير',
    'auth.demoNotice': 'حسابات العرض التوضيحي لأغراض التوضيح فقط',
    'auth.login.adminTitle': 'تسجيل دخول المدير',
    'auth.login.providerTitle': 'تسجيل دخول مقدم الخدمة',
    'auth.login.userTab': 'مستخدم',
    'auth.login.providerTab': 'مقدم خدمة',
    'auth.login.adminTab': 'مدير',
    
    // Language switching
    'language.select': 'اختر اللغة',
    'language.changedToEnglish': 'تم تغيير اللغة إلى الإنجليزية',
    'language.changedToArabic': 'تم تغيير اللغة إلى العربية',
    'language.pageWillRefresh': 'ستتم إعادة تحميل الصفحة لتطبيق التغييرات',
    'language.pageWillRefreshAr': 'ستتم إعادة تحميل الصفحة لتطبيق التغييرات',
    
    // Common words
    'common.search': 'البحث',
    'common.book': 'حجز',
    'common.view': 'عرض',
    'common.details': 'التفاصيل',
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.cancel': 'إلغاء',
    'common.confirm': 'تأكيد',
    'common.save': 'حفظ',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.add': 'إضافة',
    'common.update': 'تحديث',
    'common.close': 'إغلاق',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.submit': 'إرسال',
    'common.reset': 'إعادة تعيين',
    'common.filter': 'تصفية',
    'common.sort': 'ترتيب',
    'common.clear': 'مسح',
    'common.apply': 'تطبيق',
    'common.remove': 'إزالة',
    'common.select': 'اختيار',
    'common.choose': 'اختر',
    'common.upload': 'رفع',
    'common.download': 'تحميل',
    'common.share': 'مشاركة',
    'common.copy': 'نسخ',
    'common.refresh': 'تحديث',
    'common.print': 'طباعة',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
    'common.help': 'مساعدة',
    'common.about': 'حول',
    'common.contact': 'اتصال',
    'common.support': 'دعم',
    'common.settings': 'إعدادات',
    'common.privacy': 'خصوصية',
    'common.terms': 'شروط',
    'common.policy': 'سياسة',
    'common.copyright': 'حقوق الطبع والنشر',
    'common.allRightsReserved': 'جميع الحقوق محفوظة',
    'common.currency': 'ر.س',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.optional': 'اختياري',
    'common.required': 'مطلوب',
    'common.available': 'متاح',
    'common.unavailable': 'غير متاح',
    'common.free': 'مجاني',
    'common.paid': 'مدفوع',
    'common.total': 'المجموع',
    'common.subtotal': 'المجموع الجزئي',
    'common.tax': 'الضريبة',
    'common.discount': 'خصم',
    'common.price': 'السعر',
    'common.perNight': 'لكل ليلة',
    'common.perPerson': 'لكل شخص',
    'common.adults': 'البالغون',
    'common.children': 'الأطفال',
    'common.rooms': 'الغرف',
    'common.nights': 'الليالي',
    'common.days': 'الأيام',
    'common.date': 'التاريخ',
    'common.time': 'الوقت',
    'common.checkIn': 'تسجيل الوصول',
    'common.checkOut': 'تسجيل المغادرة',
    'common.departure': 'المغادرة',
    'common.arrival': 'الوصول',
    'common.from': 'من',
    'common.to': 'إلى',
    'common.rating': 'التقييم',
    'common.reviews': 'المراجعات',
    'common.review': 'مراجعة',
    'common.location': 'الموقع',
    'common.address': 'العنوان',
    'common.phone': 'الهاتف',
    'common.website': 'الموقع الإلكتروني',
    'common.map': 'الخريطة',
    'common.photos': 'الصور',
    'common.amenities': 'المرافق',
    'common.facilities': 'التسهيلات',
    'common.services': 'الخدمات',
    'common.features': 'المميزات',
    'common.description': 'الوصف',
    'common.overview': 'نظرة عامة',
    'common.highlights': 'النقاط المميزة',
    'common.included': 'مشمول',
    'common.excluded': 'غير مشمول',
    'common.notes': 'ملاحظات',
    'common.policies': 'السياسات',
    'common.cancellation': 'الإلغاء',
    'common.refund': 'الاسترداد',
    'common.payment': 'الدفع',
    'common.checkout': 'الدفع',
    
    // Dashboard
    'dashboard.welcome': 'أهلاً وسهلاً',
    'dashboard.overview': 'نظرة عامة على لوحة التحكم',
    'dashboard.totalBookings': 'إجمالي الحجوزات',
    'dashboard.totalBookingsDesc': 'العدد الإجمالي للحجوزات المستلمة',
    'dashboard.pendingBookings': 'الحجوزات المعلقة',
    'dashboard.pendingBookingsDesc': 'الحجوزات في انتظار التأكيد',
    'dashboard.totalRevenue': 'إجمالي الإيرادات',
    'dashboard.totalRevenueDesc': 'إجمالي الإيرادات من جميع الحجوزات',
    'dashboard.activeListings': 'القوائم النشطة',
    'dashboard.activeListingsDesc': 'قوائم الفنادق والباقات النشطة الخاصة بك',
    'dashboard.recentBookings': 'الحجوزات الأخيرة',
    'dashboard.viewAll': 'عرض الكل',
    'dashboard.monthlyBookings': 'الحجوزات الشهرية',
    'dashboard.monthlyBookingsDesc': 'عدد الحجوزات شهرياً',
    'dashboard.revenueTrend': 'اتجاه الإيرادات',
    'dashboard.revenueTrendDesc': 'الإيرادات الشهرية بالريال السعودي',
    'dashboard.bookings': 'الحجوزات',
    'dashboard.revenue': 'الإيرادات',
    'dashboard.stats': 'الإحصائيات',
    'dashboard.analytics': 'التحليلات',
    'dashboard.reports': 'التقارير',
    
    // Admin specific
    'admin.dashboard': 'لوحة تحكم المدير',
    'admin.users': 'المستخدمون',
    'admin.providers': 'مقدمو الخدمات',
    'admin.systemSettings': 'إعدادات النظام',
    'admin.userManagement': 'إدارة المستخدمين',
    'admin.providerManagement': 'إدارة مقدمي الخدمات',
    'admin.bookingManagement': 'إدارة الحجوزات',
    'admin.reviewManagement': 'إدارة المراجعات',
    'admin.totalUsers': 'إجمالي المستخدمين',
    'admin.totalProviders': 'إجمالي مقدمي الخدمات',
    'admin.systemHealth': 'صحة النظام',
    'admin.recentActivity': 'النشاط الأخير',
    
    // Bookings
    'bookings.title': 'حجوزاتي',
    'bookings.upcoming': 'القادمة',
    'bookings.past': 'السابقة',
    'bookings.cancelled': 'الملغاة',
    'bookings.pending': 'معلقة',
    'bookings.confirmed': 'مؤكدة',
    'bookings.completed': 'مكتملة',
    'bookings.bookingId': 'رقم الحجز',
    'bookings.bookingDate': 'تاريخ الحجز',
    'bookings.bookingDetails': 'تفاصيل الحجز',
    'bookings.guestDetails': 'تفاصيل الضيف',
    'bookings.contactInfo': 'معلومات الاتصال',
    'bookings.specialRequests': 'الطلبات الخاصة',
    'bookings.bookingStatus': 'حالة الحجز',
    'bookings.paymentStatus': 'حالة الدفع',
    'bookings.modifyBooking': 'تعديل الحجز',
    'bookings.cancelBooking': 'إلغاء الحجز',
    'bookings.downloadVoucher': 'تحميل القسيمة',
    'bookings.noBookings': 'لا توجد حجوزات',
    'bookings.bookingConfirmed': 'تم تأكيد الحجز',
    'bookings.bookingCancelled': 'تم إلغاء الحجز',
    'bookings.bookingModified': 'تم تعديل الحجز',
    
    // Hotels
    'hotels.searchHotels': 'البحث عن فنادق',
    'hotels.featuredHotels': 'الفنادق المميزة',
    'hotels.hotelDetails': 'تفاصيل الفندق',
    'hotels.roomTypes': 'أنواع الغرف',
    'hotels.availability': 'التوفر',
    'hotels.pricePerNight': 'السعر لكل ليلة',
    'hotels.distanceToHaram': 'المسافة إلى الحرم',
    'hotels.starRating': 'تصنيف النجوم',
    'hotels.guestRating': 'تقييم الضيوف',
    'hotels.hotelAmenities': 'مرافق الفندق',
    'hotels.roomAmenities': 'مرافق الغرفة',
    'hotels.hotelPolicies': 'سياسات الفندق',
    'hotels.cancellationPolicy': 'سياسة الإلغاء',
    'hotels.checkInTime': 'وقت تسجيل الوصول',
    'hotels.checkOutTime': 'وقت تسجيل المغادرة',
    'hotels.selectRoom': 'اختر الغرفة',
    'hotels.bookNow': 'احجز الآن',
    'hotels.viewOnMap': 'عرض على الخريطة',
    'hotels.hotelPhotos': 'صور الفندق',
    'hotels.nearbyAttractions': 'المعالم القريبة',
    'hotels.transportOptions': 'خيارات النقل',
    
    // Packages
    'packages.title': 'باقات السفر',
    'packages.featuredPackages': 'الباقات المميزة',
    'packages.packageDetails': 'تفاصيل الباقة',
    'packages.packageIncludes': 'تشمل الباقة',
    'packages.itinerary': 'خط الرحلة',
    'packages.pricePerPerson': 'السعر لكل شخص',
    'packages.duration': 'المدة',
    'packages.groupSize': 'حجم المجموعة',
    'packages.departureDate': 'تاريخ المغادرة',
    'packages.returnDate': 'تاريخ العودة',
    'packages.availableDates': 'التواريخ المتاحة',
    'packages.packageType': 'نوع الباقة',
    'packages.umrahPackage': 'باقة عمرة',
    'packages.hajjPackage': 'باقة حج',
    'packages.cityTour': 'جولة في المدينة',
    'packages.religiousTour': 'جولة دينية',
    'packages.bookPackage': 'احجز الباقة',
    'packages.packageBooking': 'حجز الباقة',
    'packages.selectDates': 'اختر التواريخ',
    'packages.selectPassengers': 'اختر المسافرين',
    'packages.packageInformation': 'معلومات الباقة',
    
    // Search
    'search.title': 'ابدأ رحلتك المقدسة',
    'search.subtitle': 'اعثر على الباقة المثالية لاحتياجاتك الروحانية',
    'search.destination': 'الوجهة',
    'search.selectLocation': 'اختر الموقع',
    'search.checkInDate': 'تاريخ الوصول',
    'search.pickDate': 'اختر تاريخاً',
    'search.duration': 'المدة',
    'search.selectDuration': 'اختر المدة',
    'search.duration3': '3 أيام',
    'search.duration7': '7 أيام',
    'search.duration14': '14 يوماً',
    'search.duration21': '21 يوماً',
    'search.duration30': '30 يوماً',
    'search.searchHotels': 'البحث عن فنادق',
    'search.bothCities': 'كلا المدينتين',
    
    // Cities
    'cities.makkah': 'مكة المكرمة',
    'cities.madinah': 'المدينة المنورة',
    
    // Testimonials
    'testimonials.location1': 'المملكة المتحدة',
    'testimonials.location2': 'كندا',
    'testimonials.location3': 'الولايات المتحدة',
    'testimonials.text1': 'جعل إنستا سفر رحلة العمرة الخاصة بي مثالية تماماً. من لحظة الحجز حتى عودتي للوطن، تم التعامل مع كل التفاصيل بعناية ومهنية.',
    'testimonials.text2': 'كوني زائرة لأول مرة للمدن المقدسة، كنت متوترة بشأن الرحلة. فريق إنستا سفر أرشدني عبر كل شيء بصبر وخبرة.',
    'testimonials.text3': 'كانت باقة الحج شاملة ومنظمة بشكل جيد. كانت أماكن الإقامة ممتازة والإرشاد الروحاني جعل التجربة ذات معنى حقيقي.',
    'testimonials.badge1': 'حاج معتمد',
    'testimonials.badge2': 'حاج لأول مرة',
    'testimonials.badge3': 'حاج',
    
    // Authentication
    'auth.signIn': 'تسجيل الدخول',
    'auth.signUp': 'التسجيل',
    'auth.login': 'دخول',
    'auth.register': 'تسجيل',
    'auth.signInTitle': 'تسجيل الدخول إلى حسابك',
    'auth.signUpDescription': 'سجل للبدء في حجز رحلتك الروحانية',
    'auth.signInDescription': 'أدخل بريدك الإلكتروني وكلمة المرور أدناه لتسجيل الدخول',
    'auth.createAccount': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.fullName': 'الاسم الكامل',
    'auth.emailPlaceholder': 'your.email@example.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.confirmPasswordPlaceholder': '••••••••',
    'auth.fullNamePlaceholder': 'اسمك الكامل',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.alreadyAccount': 'لديك حساب بالفعل؟',
    'auth.areYouProvider': 'هل أنت مقدم خدمة؟',
    'auth.registerAsProvider': 'سجل هنا',
    'auth.termsAgreement': 'بالتسجيل، أنت توافق على',
    'auth.termsOfService': 'شروط الخدمة',
    'auth.and': 'و',
    'auth.privacyPolicy': 'سياسة الخصوصية',
    'auth.registering': 'جاري إنشاء الحساب...',
    'auth.registerSuccess': 'تم التسجيل بنجاح',
    'auth.registerSuccessDescription': 'تم إنشاء حسابك بنجاح.',
    'auth.loginSuccess': 'تم تسجيل الدخول بنجاح',
    'auth.welcomeBack': 'مرحباً بعودتك إلى إنستا سفر!',
    'auth.authError': 'خطأ في المصادقة',
    'auth.authenticating': 'جاري إكمال المصادقة',
    'auth.pleaseWait': 'يرجى الانتظار بينما نتحقق من حسابك...',
    'auth.redirectingToLogin': 'جاري التوجيه إلى صفحة تسجيل الدخول...',
    'auth.unexpectedError': 'حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.',
    'auth.quickLogin': 'تسجيل دخول سريع للعرض التوضيحي',
    'auth.loginAsUser': 'تسجيل الدخول كمستخدم',
    'auth.loginAsProvider': 'تسجيل الدخول كمقدم خدمة',
    'auth.loginAsAdmin': 'تسجيل الدخول كمدير',
    'auth.demoNotice': 'حسابات العرض التوضيحي لأغراض التوضيح فقط',
    'auth.login.adminTitle': 'تسجيل دخول المدير',
    'auth.login.providerTitle': 'تسجيل دخول مقدم الخدمة',
    'auth.login.userTab': 'مستخدم',
    'auth.login.providerTab': 'مقدم خدمة',
    'auth.login.adminTab': 'مدير',
    
    // Language switching
    'language.select': 'اختر اللغة',
    'language.changedToEnglish': 'تم تغيير اللغة إلى الإنجليزية',
    'language.changedToArabic': 'تم تغيير اللغة إلى العربية',
    'language.pageWillRefresh': 'ستتم إعادة تحميل الصفحة لتطبيق التغييرات',
    'language.pageWillRefreshAr': 'ستتم إعادة تحميل الصفحة لتطبيق التغييرات',
    
    // Common words
    'common.search': 'البحث',
    'common.book': 'حجز',
    'common.view': 'عرض',
    'common.details': 'التفاصيل',
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.cancel': 'إلغاء',
    'common.confirm': 'تأكيد',
    'common.save': 'حفظ',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.add': 'إضافة',
    'common.update': 'تحديث',
    'common.close': 'إغلاق',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.submit': 'إرسال',
    'common.reset': 'إعادة تعيين',
    'common.filter': 'تصفية',
    'common.sort': 'ترتيب',
    'common.clear': 'مسح',
    'common.apply': 'تطبيق',
    'common.remove': 'إزالة',
    'common.select': 'اختيار',
    'common.choose': 'اختر',
    'common.upload': 'رفع',
    'common.download': 'تحميل',
    'common.share': 'مشاركة',
    'common.copy': 'نسخ',
    'common.refresh': 'تحديث',
    'common.print': 'طباعة',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
    'common.help': 'مساعدة',
    'common.about': 'حول',
    'common.contact': 'اتصال',
    'common.support': 'دعم',
    'common.settings': 'إعدادات',
    'common.privacy': 'خصوصية',
    'common.terms': 'شروط',
    'common.policy': 'سياسة',
    'common.copyright': 'حقوق الطبع والنشر',
    'common.allRightsReserved': 'جميع الحقوق محفوظة',
    'common.currency': 'ر.س',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.optional': 'اختياري',
    'common.required': 'مطلوب',
    'common.available': 'متاح',
    'common.unavailable': 'غير متاح',
    'common.free': 'مجاني',
    'common.paid': 'مدفوع',
    'common.total': 'المجموع',
    'common.subtotal': 'المجموع الجزئي',
    'common.tax': 'الضريبة',
    'common.discount': 'خصم',
    'common.price': 'السعر',
    'common.perNight': 'لكل ليلة',
    'common.perPerson': 'لكل شخص',
    'common.adults': 'البالغون',
    'common.children': 'الأطفال',
    'common.rooms': 'الغرف',
    'common.nights': 'الليالي',
    'common.days': 'الأيام',
    'common.date': 'التاريخ',
    'common.time': 'الوقت',
    'common.checkIn': 'تسجيل الوصول',
    'common.checkOut': 'تسجيل المغادرة',
    'common.departure': 'المغادرة',
    'common.arrival': 'الوصول',
    'common.from': 'من',
    'common.to': 'إلى',
    'common.rating': 'التقييم',
    'common.reviews': 'المراجعات',
    'common.review': 'مراجعة',
    'common.location': 'الموقع',
    'common.address': 'العنوان',
    'common.phone': 'الهاتف',
    'common.website': 'الموقع الإلكتروني',
    'common.map': 'الخريطة',
    'common.photos': 'الصور',
    'common.amenities': 'المرافق',
    'common.facilities': 'التسهيلات',
    'common.services': 'الخدمات',
    'common.features': 'المميزات',
    'common.description': 'الوصف',
    'common.overview': 'نظرة عامة',
    'common.highlights': 'النقاط المميزة',
    'common.included': 'مشمول',
    'common.excluded': 'غير مشمول',
    'common.notes': 'ملاحظات',
    'common.policies': 'السياسات',
    'common.cancellation': 'الإلغاء',
    'common.refund': 'الاسترداد',
    'common.payment': 'الدفع',
    'common.checkout': 'الدفع',
    
    // Dashboard
    'dashboard.welcome': 'أهلاً وسهلاً',
    'dashboard.overview': 'نظرة عامة على لوحة التحكم',
    'dashboard.totalBookings': 'إجمالي الحجوزات',
    'dashboard.totalBookingsDesc': 'العدد الإجمالي للحجوزات المستلمة',
    'dashboard.pendingBookings': 'الحجوزات المعلقة',
    'dashboard.pendingBookingsDesc': 'الحجوزات في انتظار التأكيد',
    'dashboard.totalRevenue': 'إجمالي الإيرادات',
    'dashboard.totalRevenueDesc': 'إجمالي الإيرادات من جميع الحجوزات',
    'dashboard.activeListings': 'القوائم النشطة',
    'dashboard.activeListingsDesc': 'قوائم الفنادق والباقات النشطة الخاصة بك',
    'dashboard.recentBookings': 'الحجوزات الأخيرة',
    'dashboard.viewAll': 'عرض الكل',
    'dashboard.monthlyBookings': 'الحجوزات الشهرية',
    'dashboard.monthlyBookingsDesc': 'عدد الحجوزات شهرياً',
    'dashboard.revenueTrend': 'اتجاه الإيرادات',
    'dashboard.revenueTrendDesc': 'الإيرادات الشهرية بالريال السعودي',
    'dashboard.bookings': 'الحجوزات',
    'dashboard.revenue': 'الإيرادات',
    'dashboard.stats': 'الإحصائيات',
    'dashboard.analytics': 'التحليلات',
    'dashboard.reports': 'التقارير',
    
    // Admin specific
    'admin.dashboard': 'لوحة تحكم المدير',
    'admin.users': 'المستخدمون',
    'admin.providers': 'مقدمو الخدمات',
    'admin.systemSettings': 'إعدادات النظام',
    'admin.userManagement': 'إدارة المستخدمين',
    'admin.providerManagement': 'إدارة مقدمي الخدمات',
    'admin.bookingManagement': 'إدارة الحجوزات',
    'admin.reviewManagement': 'إدارة المراجعات',
    'admin.totalUsers': 'إجمالي المستخدمين',
    'admin.totalProviders': 'إجمالي مقدمي الخدمات',
    'admin.systemHealth': 'صحة النظام',
    'admin.recentActivity': 'النشاط الأخير',
    
    // Bookings
    'bookings.title': 'حجوزاتي',
    'bookings.upcoming': 'القادمة',
    'bookings.past': 'السابقة',
    'bookings.cancelled': 'الملغاة',
    'bookings.pending': 'معلقة',
    'bookings.confirmed': 'مؤكدة',
    'bookings.completed': 'مكتملة',
    'bookings.bookingId': 'رقم الحجز',
    'bookings.bookingDate': 'تاريخ الحجز',
    'bookings.bookingDetails': 'تفاصيل الحجز',
    'bookings.guestDetails': 'تفاصيل الضيف',
    'bookings.contactInfo': 'معلومات الاتصال',
    'bookings.specialRequests': 'الطلبات الخاصة',
    'bookings.bookingStatus': 'حالة الحجز',
    'bookings.paymentStatus': 'حالة الدفع',
    'bookings.modifyBooking': 'تعديل الحجز',
    'bookings.cancelBooking': 'إلغاء الحجز',
    'bookings.downloadVoucher': 'تحميل القسيمة',
    'bookings.noBookings': 'لا توجد حجوزات',
    'bookings.bookingConfirmed': 'تم تأكيد الحجز',
    'bookings.bookingCancelled': 'تم إلغاء الحجز',
    'bookings.bookingModified': 'تم تعديل الحجز',
    
    // Hotels
    'hotels.searchHotels': 'البحث عن فنادق',
    'hotels.featuredHotels': 'الفنادق المميزة',
    'hotels.hotelDetails': 'تفاصيل الفندق',
    'hotels.roomTypes': 'أنواع الغرف',
    'hotels.availability': 'التوفر',
    'hotels.pricePerNight': 'السعر لكل ليلة',
    'hotels.distanceToHaram': 'المسافة إلى الحرم',
    'hotels.starRating': 'تصنيف النجوم',
    'hotels.guestRating': 'تقييم الضيوف',
    'hotels.hotelAmenities': 'مرافق الفندق',
    'hotels.roomAmenities': 'مرافق الغرفة',
    'hotels.hotelPolicies': 'سياسات الفندق',
    'hotels.cancellationPolicy': 'سياسة الإلغاء',
    'hotels.checkInTime': 'وقت تسجيل الوصول',
    'hotels.checkOutTime': 'وقت تسجيل المغادرة',
    'hotels.selectRoom': 'اختر الغرفة',
    'hotels.bookNow': 'احجز الآن',
    'hotels.viewOnMap': 'عرض على الخريطة',
    'hotels.hotelPhotos': 'صور الفندق',
    'hotels.nearbyAttractions': 'المعالم القريبة',
    'hotels.transportOptions': 'خيارات النقل',
    
    // Packages
    'packages.title': 'باقات السفر',
    'packages.featuredPackages': 'الباقات المميزة',
    'packages.packageDetails': 'تفاصيل الباقة',
    'packages.packageIncludes': 'تشمل الباقة',
    'packages.itinerary': 'خط الرحلة',
    'packages.pricePerPerson': 'السعر لكل شخص',
    'packages.duration': 'المدة',
    'packages.groupSize': 'حجم المجموعة',
    'packages.departureDate': 'تاريخ المغادرة',
    'packages.returnDate': 'تاريخ العودة',
    'packages.availableDates': 'التواريخ المتاحة',
    'packages.packageType': 'نوع الباقة',
    'packages.umrahPackage': 'باقة عمرة',
    'packages.hajjPackage': 'باقة حج',
    'packages.cityTour': 'جولة في المدينة',
    'packages.religiousTour': 'جولة دينية',
    'packages.bookPackage': 'احجز الباقة',
    'packages.packageBooking': 'حجز الباقة',
    'packages.selectDates': 'اختر التواريخ',
    'packages.selectPassengers': 'اختر المسافرين',
    'packages.packageInformation': 'معلومات الباقة',
    
    // Search
    'search.title': 'ابدأ رحلتك المقدسة',
    'search.subtitle': 'اعثر على الباقة المثالية لاحتياجاتك الروحانية',
    'search.destination': 'الوجهة',
    'search.selectLocation': 'اختر الموقع',
    'search.checkInDate': 'تاريخ الوصول',
    'search.pickDate': 'اختر تاريخاً',
    'search.duration': 'المدة',
    'search.selectDuration': 'اختر المدة',
    'search.duration3': '3 أيام',
    'search.duration7': '7 أيام',
    'search.duration14': '14 يوماً',
    'search.duration21': '21 يوماً',
    'search.duration30': '30 يوماً',
    'search.searchHotels': 'البحث عن فنادق',
    'search.bothCities': 'كلا المدينتين',
    
    // Cities
    'cities.makkah': 'مكة المكرمة',
    'cities.madinah': 'المدينة المنورة',
    
    // Testimonials
    'testimonials.location1': 'المملكة المتحدة',
    'testimonials.location2': 'كندا',
    'testimonials.location3': 'الولايات المتحدة',
    'testimonials.text1': 'جعل إنستا سفر رحلة العمرة الخاصة بي مثالية تماماً. من لحظة الحجز حتى عودتي للوطن، تم التعامل مع كل التفاصيل بعناية ومهنية.',
    'testimonials.text2': '
